backend:
  name: test-repo

# Папка для загружаемых изображений
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "home"
    label: "Главная страница"
    files:
      - name: "hero"
        label: "Главный блок"
        file: "src/content/home/hero.json"
        fields:
          - { label: "Заголовок", name: "title", widget: "string"}
          - { label: "Подзаголовок", name: "subtitle", widget: "text"}
          - { label: "Текст на кнопке", name: "button_text", widget: "string"}